package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-01-06T16:13:46.636+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZSDRFC_DEALER_PLANT")
@XmlSeeAlso({ObjectFactory.class})
public interface ZSDRFCDEALERPLANT {

    @WebMethod(operationName = "ZsdrfcDealerPlant", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZSDRFC_DEALER_PLANT:ZsdrfcDealerPlantRequest")
    @RequestWrapper(localName = "ZsdrfcDealerPlant", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdrfcDealerPlant_Type")
    @ResponseWrapper(localName = "ZsdrfcDealerPlantResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdrfcDealerPlantResponse")
    public void zsdrfcDealerPlant(
        @WebParam(name = "Dealer", targetNamespace = "")
        java.lang.String dealer,
        @WebParam(name = "Plant", targetNamespace = "")
        java.lang.String plant,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerAdd", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerAdd,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerAddr1", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerAddr1,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerAddr2", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerAddr2,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerAddr3", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerAddr3,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerCity", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerCity,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerGstin", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerGstin,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerName,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerPanNo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerPanNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerPostalCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerPostalCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerStateCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerStateCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "DealerStateDesc", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dealerStateDesc,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantAddr1", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantAddr1,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantAddr2", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantAddr2,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantAddr3", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantAddr3,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantAddress", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantAddress,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantCity", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantCity,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantEccNo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantEccNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantGstin", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantGstin,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantName,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantPostalCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantPostalCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantStateCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantStateCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "PlantStateDesc", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> plantStateDesc
    );
}
